programms/urls.py
app_name = 'programms'
from django.urls import path
from .import views 

urlpatterns = [
    path('', views.showprogram, name='show-program'),
    path('programms/<int:prog_id>/', views.current_program, name='current-program'),
]

workout_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .import views
import programms.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('programs/', programms.views.home, name='programs'),
    path('program/', include('programms.urls'), name='program'),
    path('reversed/', views.reverse, name='reverse'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coachApp/models.py
from django.db import models

# Create your models here.

programms/models.py
from django.db import models

# Create your models here.
class WorkoutProgram(models.Model):
    program_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    program_picture = models.ImageField(upload_to='program_pictures/', blank=True, null=True)

    def __str__(self):
        return self.name
    def get_brief(self):
        return self.description[:70]

class Exercise(models.Model):
    exercise_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    sport_type = models.CharField(max_length=50)
    exercise_picture = models.ImageField(upload_to='exercise_pictures/', blank=True, null=True)
    
    def __str__(self):
        return self.name


class ExerciseWorkoutProgram(models.Model):
    id = models.AutoField(primary_key=True)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    program = models.ForeignKey(WorkoutProgram, on_delete=models.CASCADE)

workout_project/models.py
from django.db import models

class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100)
    email = models.EmailField()
    sessions_quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.username

coachApp/views.py
from django.shortcuts import render

# Create your views here.

programms/views.py
from django.shortcuts import render, get_list_or_404
from .models import WorkoutProgram, Exercise, ExerciseWorkoutProgram
# Create your views here.
def home(request):
    programs = WorkoutProgram.objects
    return render(request, 'programms.html', {'programs' : programs})

def showprogram(request):
    exercise = Exercise.objects
    return render(request, 'split.html', {'exercise' : exercise})

def current_program(request, prog_id):
    current_prog = WorkoutProgram.objects.get(pk=prog_id)
    associated_exercises = ExerciseWorkoutProgram.objects.filter(program=current_prog)
    return render(request, 'progdescription.html', {'current': current_prog, 'associated_exercises': associated_exercises})

workout_project/views.py
from django.http import HttpResponse
from django.shortcuts import render
def home(request):
    return render(request, 'home.html')

def reverse(request):
    user_message = request.GET['message']
    word_count = len(user_message.split())
    reversed_message = user_message[::-1]
    return render(request, 'reverse.html', {'message':user_message, 'rev_message':reversed_message, 'counter':word_count})

programms/templates/progdescription.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ current.name}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="jumbotron text-center" style="background-color: rgb(140, 157, 235);">
       
        <div class="jumbotron text-center">
            <h1>{{ current.name }}</h1>
            <h2>{{ current.description }}</h2>
           <img class="rounded mx-auto d-block" style="width: 22cm"  src="{{ current.program_picture.url }}" alt="err404">
        </div>
        

<h2>Exercises:</h2>
  <h2><ol>
    {% for exercise in associated_exercises %}
        <li>
            <h1>{{ exercise.exercise.name }} - {{ exercise.exercise.description }}</h1>
            <img src="{{ exercise.exercise.exercise_picture.url }}" alt="{{ exercise.exercise.name }} Picture">
        </li>
    {% endfor %}
  </ol></h2>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

programms/templates/programms.html
{% extends 'base.html' %}

{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Programms</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="jumbotron text-center" style="background-color: rgb(140, 157, 235);">
        {% for i in programs.all %}
        <div class="jumbotron text-center">
           
            <a href="{% url 'programms:show-program' %}"><h1>Program: {{ i.name }} </h1></a>
            <h3>Description: {{ i.get_brief }} ... <a href="{% url 'programms:current-program' prog_id=i.program_id %}">read more</a></h3>
            <img class="rounded mx-auto d-block" style="width: 22cm" src="{{ i.program_picture.url }}" alt="err404">
            
        </div>
    {% endfor %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}

programms/templates/programms/programms.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="jumbotron, text-center" style="background-color: rgb(69, 97, 97);">
    {% for i programs.all %}
        <h1>Program Name: {{ programs.name }} </h1>
        <p>Description: {{programs.description}}</p>
        <img src="programs.program_picture" alt="">
</div>
{% endfor %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

programms/templates/split.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Split</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="jumbotron text-center" style="background-color: rgb(140, 157, 235);">
        {% for i in exercise.all %}
        <div class="jumbotron text-center">
            <h1>Exercise Name: {{ i.name }} </h1>
            <h3>Description: {{ i.description }}</h3>
            <img class="card-img-top" style="width: 22cm" src="{{ i.exercise_picture.url }}" alt="err404">
        </div>
    {% endfor %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/base.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-transparent">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Workout_Project</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" target='_blank' href="https://web.telegram.org/k/#@p_warrior13" rel="noopener noreferrer">Telegram</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" target='_blank' rel="noopener noreferrer" href="{% static 'workout уровень.pdf' %}">1st level GIFT</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="programs">Programs</a>
          </li>
          <li class="nav-item dropdown">
            
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="jumbotron text-center" style="background-color: rgb(113, 113, 221);">
    <h1>Hello User welcome to Profile page!</h1>

    <form action="{% url 'reverse' %}" method="post">
        {% csrf_token %}
        <textarea name="message" cols="30" rows="10">Type Something here...</textarea>
        <br> 
        <input class="btn btn-success" type="submit" value="Reverse!">
    </form>
    <br>
    <img src="{% static 'ZK.jpg' %}" alt="err404">
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

{% endblock %}

templates/profile.html
<h1>Hello User welcome to Profile page!</h1>

<form action="/profile2">
    <textarea name="" id="message" cols="30" rows="10">
        Type Something here...</textarea>
        <br> 
        <input type="submit" value="Reverse!">
</form>

templates/reverse.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reverse Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="jumbotron text-center" style="background-color: rgb(253, 249, 0);">
         <h1>Output Original data</h1>
<h2 style="color: blueviolet;">Number of words is/are: {{counter}}</h2>
<p style="color: rgb(7, 252, 39);">{{message}}</p>
    </div>
   
<div class="jumbotron text-center" style="background-color: rgb(0, 25, 253);">
    <h1>Output reversed data</h1>
<p style="color: rgb(255, 1, 1);">{{rev_message}}</p>
<a href="/" class="btn btn-success">Return back</a>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>